config/routes.rb
Rails.application.routes.draw do
  get 'articulos/new'

  resources :articulos

   root 'bienvenido#index'

end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  def index
    @articulos = Articulo.all
  end

  def show
    @articulo = Articulo.find(params[:id])
  end

  def new

  end
  
  def create
  @articulo = Articulo.new(articulo_params)
 
  @articulo.save
  redirect_to @articulo
end
 
private
  def articulo_params
    params.require(:articulo).permit(:titular, :contenido)
  end

end 

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  	@name="Jorge Eliecer Hernandez"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/views/articulos/index.html.erb
<h1>Listando Artículos</h1>
 
<table>
  <tr>
    <th>Titular</th>
    <th>Contenido</th>
  </tr>
 
  <% @articulos.each do |articulo| %>
    <tr>
      <td><%= articulo.titular %></td>
      <td><%= articulo.contenido %></td>
    </tr>
  <% end %>
</table>

app/views/articulos/new.html.erb
<h1>Nuevo Artículo</h1>


<%= form_for :articulo, url: articulos_path do |f| %>
  <p>
    <%= f.label :titular  %><br>
    <%= f.text_field :titular %>
  </p>
 
  <p>
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
  </p>
 
  <p>
    <%= f.submit 'Guardar Artículo' %>
  </p>
<% end %>

app/views/articulos/show.html.erb
<p>
  <strong>Titular:</strong>
  <%= @articulo.titular %>
</p>
 
<p>
  <strong>Contenido:</strong>
  <%= @articulo.contenido %>
</p>

app/views/bienvenido/index.html.erb
<h1>Bienvenido</h1>
<p>primera pagina creada</p>

<h3>Bienvenido</h3><%= @name %>
<h3>Bienvenido: <%= @name %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>